[package]
name = "test-plan-discv5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test-plan-discv5"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
# TODO: update discv5 once the PR is merged: https://github.com/sigp/discv5/pull/110
discv5 = { git = "https://github.com/ackintosh/discv5.git", branch = "fix-issue-108" }
if-addrs = "0.7.0"
ipnetwork = "0.19.0"
serde = "1.0.137"
serde_json = "1.0.81"
# TODO: Update testground once the next version of v0.1.1 has been released.
testground = { git = "https://github.com/testground/sdk-rust.git", rev = "5c50ba4f63d2aff6b815cfbfcb0c8f9e4d73809e" }
tokio = { version = "1.18.2", features = ["macros"] }
tokio-stream = "0.1.8"
tracing = "0.1.33"
tracing-subscriber = "0.3.11"
