[package]
name = "discv5-testground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "discv5-testground"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
# TODO: update discv5 once the next version (beta.14) has been released: https://github.com/sigp/discv5/pull/118
# Specifying the patched revision for now:  https://github.com/sigp/discv5/pull/122
discv5 = { git = "https://github.com/sigp/discv5.git", rev = "e02821e75ad2babee934698d9073ee9813bc01ae" }
if-addrs = "0.7.0"
ipnetwork = "0.19.0"
serde = "1.0.137"
serde_json = "1.0.81"
# See: https://github.com/testground/sdk-rust/pull/22
testground = { git = "https://github.com/ackintosh/sdk-rust.git", rev = "e5fa2ca77d43047536bd215e6ee6e813face81c8" }
tokio = { version = "1.19.2", features = ["macros"] }
tokio-stream = "0.1.9"
tracing = "0.1.33"
tracing-subscriber = "0.3.11"
