[package]
name = "discv5-testground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "discv5-testground"
path = "src/main.rs"

[dependencies]
chrono = "0.4.22"
# TODO: update discv5 once the next version (beta.14) has been released: https://github.com/sigp/discv5/pull/118
# Specifying the patched revision for now:  https://github.com/sigp/discv5/pull/122
discv5 = { git = "https://github.com/sigp/discv5.git", rev = "e02821e75ad2babee934698d9073ee9813bc01ae" }
rand_xorshift = "0.3.0"
serde = "1.0.145"
serde_json = "1.0.85"
# TODO: update testground once the next version has been released.
testground = { git = "https://github.com/testground/sdk-rust.git", rev = "0a1d439f5ca63daf8c1d8d99e5ab1752c6351a25" }
tokio = { version = "1.21.2", features = ["macros"] }
tokio-stream = "0.1.10"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
