[package]
name = "discv5-testground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "discv5-testground"
path = "src/main.rs"

[dependencies]
chrono = "0.4.26"
discv5 = { git = "https://github.com/ackintosh/discv5.git", rev = "0b11b6872622437f3b85782bcd6878506fc519ef" }
rand_xorshift = "0.3.0"
serde = "1.0.164"
serde_json = "1.0.97"
testground = "0.4.0"
tokio = { version = "1.28.2", features = ["macros"] }
tokio-stream = "0.1.14"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
