name = "test-plan-discv5"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "find-node"
instances = { min = 3, max = 100, default = 3 }