name = "discv5-testground"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "find-node"
instances = { min = 3, max = 100, default = 3 }

  [testcases.params]
  latency = { type = "int", desc = "latency between peers", unit = "ms", default = 100 }

[[testcases]]
name = "eclipse-attack-monopolizing-connections"
instances = { min = 3, max = 100, default = 3 }

  [testcases.params]
  latency = { type = "int", desc = "latency between peers", unit = "ms", default = 100 }
