name = "discv5-testground"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

# FINDNODE
[[testcases]]
name = "find-node"
instances = { min = 3, max = 100, default = 3 }

  [testcases.params]
  latency = { type = "int", desc = "latency between peers", unit = "ms", default = 100 }

# Eclipse attack by table poisoning
[[testcases]]
name = "eclipse-attack-table-poisoning"
instances = { min = 20, max = 20, default = 20 }

  [testcases.params]
  latency = { type = "int", desc = "latency between peers", unit = "ms", default = 100 }
