name = "discv5-testground"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

# FINDNODE
[[testcases]]
name = "find-node"
instances = { min = 3, max = 100, default = 3 }

  [testcases.params]
  latency = { type = "int", desc = "Latency between peers.", unit = "ms", default = 100 }

# Eclipse attack by monopolizing by incoming nodes
[[testcases]]
name = "eclipse-attack-monopolizing-by-incoming-nodes"
# The number of `instances` is fixed to 20 in this test case. For more detail,
# see `compositions/eclipse-attack-monopolizing-by-incoming-nodes.toml`.
instances = { min = 20, max = 20, default = 20 }

  [testcases.params]
  latency = { type = "int", desc = "Latency between peers.", unit = "ms", default = 100 }

  # Params for the `victim` group
  incoming_bucket_limit = { type = "int", desc = "A maximum limit to the number of incoming nodes per bucket.", default = 16 }

# IP change
[[testcases]]
name = "ip-change"
instances = { min = 3, max = 100, default = 3 }

  [testcases.params]
  latency = { type = "int", desc = "Latency between peers.", unit = "ms", default = 100 }

  # discv5 params
  vote_duration = { type = "int", desc = "The interval over which votes are remembered when determining our external IP.", unit = "sec", default = 5 }
  ping_interval = { type = "int", desc = "The time between pings to ensure connectivity amongst connected nodes.", unit = "sec", default = 1 }

  # simulation params
  duration_before = { type = "int", desc = "Duration to run the simulation before changing IP address.", default = 5, unit="sec" }
  duration_after = { type = "int", desc = "Duration to run the simulation after changing IP address.", default = 15, unit="sec" }

# ENR update
[[testcases]]
name = "enr-update"
instances = { min = 11, max = 100, default = 11 }

  [testcases.params]
  latency = { type = "int", desc = "Latency between peers.", unit = "ms", default = 100 }

  # discv5 params
  ping_interval = { type = "int", desc = "The time between pings.", unit = "sec", default = 30 }
