[metadata]
name = "eclipse-attack-monopolizing-by-incoming-nodes"
author = "Akihito Nakano"

[global]
plan = "discv5-testground"
case = "eclipse-attack-monopolizing-by-incoming-nodes"
total_instances = 20
builder = "docker:generic"
runner = "local:docker"
disable_metrics = false

[[groups]]
id = "victim"
  [groups.instances]
  count = 1
  [groups.run]
    [groups.run.test_params]
    # This parameter sets a maximum limit to the number of incoming nodes per bucket. If you comment out this parameter,
    # the victim node emits "Table full" error since the victim's routing bucket is full of the "incoming" attacker node
    # ids.
    incoming_bucket_limit = "8"

[[groups]]
id = "honest"
  [groups.instances]
  count = 1
  [groups.run]
    [groups.run.test_params]

[[groups]]
id = "attackers"
  [groups.instances]
  count = 18
  [groups.run]
    [groups.run.test_params]
