on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  testground:
    name: Testground runs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: test-plan-discv5

      - name: Checkout testground
        uses: actions/checkout@v2
        with:
          path: testground
          repository: testground/testground

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Install testground
        run: make install
        working-directory: testground

      - name: Run testground daemon
        run: testground daemon &

      # ########################################
      # Run example plan
      # NOTE:
      #   * Testground starts containers (e.g. InfluxDB) on its first run.
      #   * In order to ensure that the containers are ready at running `find-node` plan later, run the example plan as trigger for the startups.
      # ########################################
      - name: Checkout sdk-rust
        uses: actions/checkout@v2
        with:
          path: sdk-rust
          repository: testground/sdk-rust

      - name: Import example plan
        run: testground plan import --from sdk-rust

      - name: Run example plan
        run: |
          testground run single \
            --plan=sdk-rust \
            --testcase=example \
            --builder=docker:generic \
            --runner=local:docker \
            --instances=1 \
            --wait

      - name: Wait until InfluxDB ready
        run: test-plan-discv5/.github/wait_until_influxdb_ready.sh

      # ########################################
      # Run find-node test plan
      # ########################################
      - name: Import test plans from test-plan-discv5
        run: testground plan import --from test-plan-discv5

      - name: Run test-plan-discv5:find-node
        run: |
          testground run single \
            --plan=test-plan-discv5 \
            --testcase=find-node \
            --builder=docker:generic \
            --runner=local:docker \
            --instances=3 \
            --wait
